pipeline {
  agent {
    docker { image 'node:16-alpine' }
  }
  stages {
    stage('Test') {
      steps {
        sh 'node --version'
      }
  stages {
    stage('deploy') {
      steps {
        echo 'Hello from jenkins'
      }
    }
  }
